- name: Install Nginx with Virtual Hosts
  hosts: webservers
  remote_user: runner
  become: true
  become_method: sudo
  gather_facts: false

  vars:
    sites:
      - etis.com
      - fizfak.com
      - mehmat.ru

  roles:
    - nginx_vhosts
