- name: Install Nginx
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: present

- name: Copy Nginx config from template
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/site-{{ item }}.conf
    owner: root
    group: root
    mode: "0644"
  loop: "{{ sites }}"
  notify: Restart Nginx

- name: Create site folders
  ansible.builtin.file:
    path: /var/www/{{ item }}/
    state: directory
    mode: "0755"
  loop: "{{ sites }}"

- name: Copy index from template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/{{ item }}/index.html
    owner: root
    group: root
    mode: "0644"
  loop: "{{ sites }}"

- name: Force Nginx restart
  ansible.builtin.systemd:
    name: nginx
    state: restarted
